# Artificial Neural Network Classification


### Importing the libraries

In [137]:
import pandas as pd
import numpy as np
import tensorflow as tf

## Part 1 - Data Preprocessing

In [138]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Importing the dataset

In [139]:
dataset = pd.read_csv('/Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [140]:
dataset
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [141]:
print(X[:,1])

['France' 'Spain' 'France' ... 'France' 'Germany' 'France']


### Encoding categorical data

In [142]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


Label Encoding the "Gender" column

In [143]:
X[:, 2] = le.fit_transform(X[:, 2])
X[:, 2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

One Hot Encoding the "Geography" column

In [144]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [145]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0 )

In [146]:
X_test.shape
X_train.shape

(8000, 12)

In [147]:
y_test.shape
y_train.shape

(8000,)

### Feature Scaling

In [148]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train.shape

(8000, 12)

## Part 2 - Building the ANN

### Initializing the ANN

In [149]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [150]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [151]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the third hidden layer

In [152]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [153]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [154]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [155]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [160]:
ann.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3349 - accuracy: 0.8633
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3326 - accuracy: 0.8644
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3325 - accuracy: 0.8646
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3318 - accuracy: 0.8634
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3325 - accuracy: 0.8639
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3299 - accuracy: 0.8639
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3311 - accuracy: 0.8664
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3319 - accuracy: 0.8640
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3315 - accuracy: 0.8625
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3300 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [157]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [158]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [159]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1509   86]
 [ 198  207]]


0.858